inherit_from: ../.rubocop.yml

require:
  - rubocop-rspec

GitlabSecurity/PublicSend:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Metrics/BlockLength:
  Max: 250

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/ContextWording:
  Enabled: true
  Prefixes: [when, with, without, if, where, for, as, after, upon, using]

RSpec/ExampleLength:
  Max: 10

RSpec/MessageExpectation:
  Enabled: true

RSpec/NestedGroups:
  Enabled: true
  Max: 6
